# COVID Cough Capstone Project- Data Wrangling 

Where is the data coming from?
https://www.nature.com/articles/s41597-021-00937-4#Sec7

What is the problem you are trying to solve? 

**Build a cough detection model using 25,000 recorded sound datasets that characterizes if a person has a respiratory illness or not based on provided personal information.**

#### Importing Libraries

In [17]:
#pip install webm

In [6]:

import os, json 
import pandas as pd
import numpy as np
import ffmpeg 
from datetime import datetime
from sklearn.preprocessing import OneHotEncoder


In [7]:
#path_to_files = '/Users/janetshirinyan/Desktop/Jenya/COVIDCoughCapstone/public_dataset/'
path_to_files = '/Users/yevheniyashevchenko/Documents - Yevheniya’s MacBook Pro/COVIDCoughCapstone/public_dataset/'
json_files = [loc_json for loc_json in os.listdir(path_to_files) if loc_json.endswith('.json')]
#print(json_files) shows all files end with .json 

#### Loading the Data

In [8]:
#load json file into dict 

output_list = []
for i,file in enumerate(json_files):
    data_dict = {}
    with open(path_to_files + file,"r") as json_open:
        data = json.loads(json_open.read())
        #print(data)
        for k,v in data.items(): 
            data_dict[k]= v
    output_list.append(data_dict)
#data_dict = {k:[v] for k,v in data.items()}
#print(data_dict)

        
#print(df)      
        

In [9]:
print(len(output_list))

27550


In [10]:
df = pd.DataFrame(output_list)

In [11]:
print(df.head())

                           datetime cough_detected latitude longitude  age  \
0  2020-11-26T04:14:12.833777+00:00         0.1674     46.2       7.4  NaN   
1  2020-04-11T19:37:13.279037+00:00         0.0396      NaN       NaN  NaN   
2  2020-11-27T12:08:05.795269+00:00         0.8014     48.3      -1.5   67   
3  2020-04-14T06:45:05.925650+00:00         0.6086     39.8      64.4   22   
4  2020-04-19T07:58:56.194180+00:00         0.0977     13.7     -89.2   20   

   gender respiratory_condition fever_muscle_pain   status expert_labels_1  \
0     NaN                   NaN               NaN      NaN             NaN   
1     NaN                   NaN               NaN      NaN             NaN   
2  female                 False             False  healthy             NaN   
3    male                 False             False  healthy             NaN   
4    male                  True             False  healthy             NaN   

  expert_labels_2 expert_labels_3 expert_labels_4  
0         

In [12]:
df.dtypes

datetime                 object
cough_detected           object
latitude                 object
longitude                object
age                      object
gender                   object
respiratory_condition    object
fever_muscle_pain        object
status                   object
expert_labels_1          object
expert_labels_2          object
expert_labels_3          object
expert_labels_4          object
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27550 entries, 0 to 27549
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   datetime               27550 non-null  object
 1   cough_detected         27550 non-null  object
 2   latitude               16084 non-null  object
 3   longitude              16084 non-null  object
 4   age                    15218 non-null  object
 5   gender                 16224 non-null  object
 6   respiratory_condition  16224 non-null  object
 7   fever_muscle_pain      16224 non-null  object
 8   status                 16224 non-null  object
 9   expert_labels_1        820 non-null    object
 10  expert_labels_2        820 non-null    object
 11  expert_labels_3        820 non-null    object
 12  expert_labels_4        820 non-null    object
dtypes: object(13)
memory usage: 2.7+ MB


**Loading the audio files**

In [14]:
fileExt = ['.webm', '.ogg']
webm_files = [files for files in os.listdir(path_to_files) if files.endswith(tuple(fileExt))]


In [15]:
#Add all sound files into a list 
audios = []

for file in webm_files: 
    with open(path_to_files + file) as sound_files:
        audios.append(sound_files)
        

In [16]:
print(len(audios)) 

27550


In [17]:
print(audios[0]) 


<_io.TextIOWrapper name='/Users/yevheniyashevchenko/Documents - Yevheniya’s MacBook Pro/COVIDCoughCapstone/public_dataset/cf593695-ce85-4a56-81c6-14617de66f71.ogg' mode='r' encoding='UTF-8'>


**Convert file formats from .webm & .ogg into .wav**

In [18]:
import time
from tqdm import tqdm
from os import path
from pydub import AudioSegment 

In [19]:

for i,s in enumerate(audios):
    # for i in tqdm(range(27550), desc = 'tqdm() Progress Bar'):
    #     time.sleep(0.5)
    with open(path_to_files + webm_files[i],"rb") as s_:
        sound = AudioSegment.from_file(s_)
        

KeyboardInterrupt: 

### Cleaning, Transforming, and Visualizing

The end goal of data cleaning is to have tidy data. When data is tidy:

Each variable has a column.
Each observation forms a row.

In [20]:
#Load the data columns
df.head(3)

datetime cough_detected latitude longitude  age  \
0  2020-11-26T04:14:12.833777+00:00         0.1674     46.2       7.4  NaN   
1  2020-04-11T19:37:13.279037+00:00         0.0396      NaN       NaN  NaN   
2  2020-11-27T12:08:05.795269+00:00         0.8014     48.3      -1.5   67   

   gender respiratory_condition fever_muscle_pain   status expert_labels_1  \
0     NaN                   NaN               NaN      NaN             NaN   
1     NaN                   NaN               NaN      NaN             NaN   
2  female                 False             False  healthy             NaN   

  expert_labels_2 expert_labels_3 expert_labels_4  
0             NaN             NaN             NaN  
1             NaN             NaN             NaN  
2             NaN             NaN             NaN

In [21]:
# def check_date(x):
#     try:
#         return datetime.strptime(i,'%y-%m-%dT%H:%M:%S%z')
#     except:
#         print(x)
# df["datetime"].apply(lambda x: check_date(x))

In [22]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [23]:
df.head()

datetime cough_detected latitude longitude  age  \
0 2020-11-26 04:14:12.833777+00:00         0.1674     46.2       7.4  NaN   
1 2020-04-11 19:37:13.279037+00:00         0.0396      NaN       NaN  NaN   
2 2020-11-27 12:08:05.795269+00:00         0.8014     48.3      -1.5   67   
3 2020-04-14 06:45:05.925650+00:00         0.6086     39.8      64.4   22   
4 2020-04-19 07:58:56.194180+00:00         0.0977     13.7     -89.2   20   

   gender respiratory_condition fever_muscle_pain   status expert_labels_1  \
0     NaN                   NaN               NaN      NaN             NaN   
1     NaN                   NaN               NaN      NaN             NaN   
2  female                 False             False  healthy             NaN   
3    male                 False             False  healthy             NaN   
4    male                  True             False  healthy             NaN   

  expert_labels_2 expert_labels_3 expert_labels_4  
0             NaN             NaN             NaN  
1             NaN             NaN             NaN  
2             NaN             NaN             NaN  
3             NaN             NaN             NaN  
4             NaN             NaN             NaN

In [24]:
expert_columns = [x for x in df.columns if 'expert_' in x]

In [25]:
expert_columns

['expert_labels_1', 'expert_labels_2', 'expert_labels_3', 'expert_labels_4']

In [26]:
col = expert_columns[3]

In [27]:
print(col)

expert_labels_4


In [28]:
def extract_keys(x):
    if isinstance(x, dict):
        return list(x.keys())
    return []

In [29]:
def create_row_expert_dict(x, col_dict,col_name):
    if isinstance(x, dict):
        output = {}
        for key in list(col_dict.keys()):
            if key in x:
                output[col_name+'_'+key] = x[key]
        return output
    return col_dict

In [30]:
import numpy as np

In [31]:
for col in expert_columns:
    col_extracted_keys = df[col].apply(lambda x: extract_keys(x))
    col_keys = []
    for row in col_extracted_keys: col_keys = list(np.unique(col_keys + row))
    col_dict = {x: False for x in col_keys}
    df_expert = pd.DataFrame(df[col].apply(lambda x: create_row_expert_dict(x, col_dict,col)).to_dict()).T
    df = pd.concat([df,df_expert], axis=1)
    

In [32]:
for k in col_keys:
    df = df.drop([k], axis=1)


In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27550 entries, 0 to 27549
Data columns (total 53 columns):
 #   Column                      Non-Null Count  Dtype              
---  ------                      --------------  -----              
 0   datetime                    27550 non-null  datetime64[ns, UTC]
 1   cough_detected              27550 non-null  object             
 2   latitude                    16084 non-null  object             
 3   longitude                   16084 non-null  object             
 4   age                         15218 non-null  object             
 5   gender                      16224 non-null  object             
 6   respiratory_condition       16224 non-null  object             
 7   fever_muscle_pain           16224 non-null  object             
 8   status                      16224 non-null  object             
 9   expert_labels_1             820 non-null    object             
 10  expert_labels_2             820 non-null    object        

In [34]:
print(col_keys)
df['expert_labels_1']

['choking', 'congestion', 'cough_type', 'diagnosis', 'dyspnea', 'nothing', 'quality', 'severity', 'stridor', 'wheezing']


0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
27545    NaN
27546    NaN
27547    NaN
27548    NaN
27549    NaN
Name: expert_labels_1, Length: 27550, dtype: object

In [35]:
df.columns
df['expert_labels_3_diagnosis'].value_counts()

upper_infection        364
healthy_cough          198
lower_infection        194
obstructive_disease     35
COVID-19                 1
Name: expert_labels_3_diagnosis, dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27550 entries, 0 to 27549
Data columns (total 53 columns):
 #   Column                      Non-Null Count  Dtype              
---  ------                      --------------  -----              
 0   datetime                    27550 non-null  datetime64[ns, UTC]
 1   cough_detected              27550 non-null  object             
 2   latitude                    16084 non-null  object             
 3   longitude                   16084 non-null  object             
 4   age                         15218 non-null  object             
 5   gender                      16224 non-null  object             
 6   respiratory_condition       16224 non-null  object             
 7   fever_muscle_pain           16224 non-null  object             
 8   status                      16224 non-null  object             
 9   expert_labels_1             820 non-null    object             
 10  expert_labels_2             820 non-null    object        

In [37]:
#Looking inside the dictionaries in expert_labels_1
selected_rows = df[~df['expert_labels_1'].isnull()]
print(selected_rows)

                              datetime cough_detected latitude longitude  age  \
8     2020-04-26 13:44:03.378644+00:00         0.9460     39.5      -5.9   44   
35    2020-04-13 14:54:52.984757+00:00         0.9329     41.0      71.1   19   
55    2020-04-26 14:38:40.121396+00:00         0.9517     38.5      27.1   19   
57    2020-04-13 15:30:25.003793+00:00         0.9920     41.4      69.2   17   
108   2020-04-10 08:58:49.494444+00:00         0.8816      NaN       NaN   55   
...                                ...            ...      ...       ...  ...   
27386 2020-04-28 02:22:22.910712+00:00         0.9968    -25.5     -49.3   31   
27393 2020-05-06 12:26:51.856110+00:00         0.7775     40.8      72.3  NaN   
27400 2020-05-06 02:02:49.313148+00:00         0.9377     41.7      61.0  NaN   
27490 2020-04-17 11:50:00.459583+00:00         0.9668     48.9       2.8  NaN   
27503 2020-05-13 06:26:52.748027+00:00         0.9932      NaN       NaN   53   

       gender respiratory_c

In [38]:
print(col_keys)

['choking', 'congestion', 'cough_type', 'diagnosis', 'dyspnea', 'nothing', 'quality', 'severity', 'stridor', 'wheezing']


### Taking a closer look at other columns 

In [39]:
df['gender'].unique()

array([nan, 'female', 'male', 'other'], dtype=object)

In [40]:
df['age'].unique()

array([nan, '67', '22', '20', '36', '25', '77', '44', '21', '51', '38',
       '26', '39', '50', '34', '46', '47', '35', '24', '19', '057', '33',
       '17', '42', '62', '16', '70', '41', '13', '55', '40', '8', '60',
       '15', '28', '37', '59', '43', '18', '57', '45', '56', '23', '31',
       '27', '3', '65', '14', '29', '30', '73', '32', '48', '63', '52',
       '66', '68', '75', '54', '53', '12', '72', '69', '49', '11', '58',
       '61', '64', '9', '83', '80', '1', '71', '102', '2', '040', '6',
       '4', '82', '74', '5', '96', '76', '79', '78', '81', '90', '84',
       '10', '86', '064', '04', '89', '01', '97', '99', '7', '91', '05',
       '21.2', '6.5', '059', '98'], dtype=object)

In [41]:
#Leave NAN and changed the values to floats
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'].unique()

array([  nan,  67. ,  22. ,  20. ,  36. ,  25. ,  77. ,  44. ,  21. ,
        51. ,  38. ,  26. ,  39. ,  50. ,  34. ,  46. ,  47. ,  35. ,
        24. ,  19. ,  57. ,  33. ,  17. ,  42. ,  62. ,  16. ,  70. ,
        41. ,  13. ,  55. ,  40. ,   8. ,  60. ,  15. ,  28. ,  37. ,
        59. ,  43. ,  18. ,  45. ,  56. ,  23. ,  31. ,  27. ,   3. ,
        65. ,  14. ,  29. ,  30. ,  73. ,  32. ,  48. ,  63. ,  52. ,
        66. ,  68. ,  75. ,  54. ,  53. ,  12. ,  72. ,  69. ,  49. ,
        11. ,  58. ,  61. ,  64. ,   9. ,  83. ,  80. ,   1. ,  71. ,
       102. ,   2. ,   6. ,   4. ,  82. ,  74. ,   5. ,  96. ,  76. ,
        79. ,  78. ,  81. ,  90. ,  84. ,  10. ,  86. ,  89. ,  97. ,
        99. ,   7. ,  91. ,  21.2,   6.5,  98. ])

In [42]:
df['cough_detected'] = df['cough_detected'].astype(float)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27550 entries, 0 to 27549
Data columns (total 53 columns):
 #   Column                      Non-Null Count  Dtype              
---  ------                      --------------  -----              
 0   datetime                    27550 non-null  datetime64[ns, UTC]
 1   cough_detected              27550 non-null  float64            
 2   latitude                    16084 non-null  object             
 3   longitude                   16084 non-null  object             
 4   age                         15218 non-null  float64            
 5   gender                      16224 non-null  object             
 6   respiratory_condition       16224 non-null  object             
 7   fever_muscle_pain           16224 non-null  object             
 8   status                      16224 non-null  object             
 9   expert_labels_1             820 non-null    object             
 10  expert_labels_2             820 non-null    object        

In [44]:
df.isnull().sum()

datetime                          0
cough_detected                    0
latitude                      11466
longitude                     11466
age                           12332
gender                        11326
respiratory_condition         11326
fever_muscle_pain             11326
status                        11326
expert_labels_1               26730
expert_labels_2               26730
expert_labels_3               26730
expert_labels_4               26730
expert_labels_1_choking       26730
expert_labels_1_congestion    26730
expert_labels_1_cough_type    26748
expert_labels_1_diagnosis     26748
expert_labels_1_dyspnea       26730
expert_labels_1_nothing       26730
expert_labels_1_quality       26730
expert_labels_1_severity      26748
expert_labels_1_stridor       26730
expert_labels_1_wheezing      26730
expert_labels_2_choking       26730
expert_labels_2_congestion    26730
expert_labels_2_cough_type    26749
expert_labels_2_diagnosis     26748
expert_labels_2_dyspnea     

In [45]:
df['fever_muscle_pain'].unique()

array([nan, 'False', 'True'], dtype=object)

In [46]:
df['respiratory_condition'].unique()

array([nan, 'False', 'True'], dtype=object)

In [57]:
df['expert_labels_2_severity'].unique()

array([nan, 'mild', 'unknown', 'severe', 'pseudocough'], dtype=object)

In [52]:
df['status'].unique()

array([nan, 'healthy', 'COVID-19', 'symptomatic'], dtype=object)

In [47]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")

In [48]:
def from_coords_to_city_country(x):
    lat = x['latitude']
    long = x['longitude']
    if pd.isna(lat) or pd.isna(long):
        return np.nan, np.nan
    coord = f"{str(lat)}, {str(long)}"
    location = geolocator.reverse(coord, exactly_one=True)
    address = location.raw['address']
    city = address.get('city', np.nan)
    country = address.get('country', np.nan)
    print('.')
    return city, country

In [49]:
location_out = df[['latitude','longitude']].sample(10).apply(lambda x: from_coords_to_city_country(x), axis=1)


.
.
.
.
.


In [50]:
location_out

12403                               (nan, nan)
11297                       (nan, Oʻzbekiston)
14582                               (nan, nan)
21721                       (nan, Oʻzbekiston)
13741                        (nan, Кыргызстан)
4284                      (nan, United States)
4125     (nan, Schweiz/Suisse/Svizzera/Svizra)
18341                               (nan, nan)
22349                               (nan, nan)
12730                               (nan, nan)
dtype: object